export enum Collections {
    Users = 'users',
    UserPets = 'pets',
    UserFeeds = 'feeds',
    Terms = 'terms',
    AuthTokens = 'authTokens',
    Playground = 'playground',
    UserActions = 'userActions',
    PushSettings = 'pushSettings',
    Payments = 'payments',
    CardInformations = 'cardInformations',
    Banners = 'banners',
    Products = 'products',
    Stores = 'stores',
    Notifications = 'notifications',
    ShippingDestination = 'shippingDestination',
}
